folio-org/mod-courses

CONTRIBUTING.md, MODEL.md, README.md, src/main/java/org/folio/rest/impl/CourseAPI.java
Added missing CONTRIBUTING.md
Please fix IDE. We do not use license headers in source code files.
See https://dev.folio.org/guidelines/contributing/#no-license-header
I noticed a couple of other things:
The MODEL.md document "APIs" section refers to RAMLs that seem to have been removed.
Also in MODEL.md document, the explanation of "schedule.json" is confusing about "sections".
Similarly with its description in the schema file.
=> FOLIO-722 minor tidy for initial repo setup

descriptors/ModuleDescriptor-template.json
As per other mod-* folio-org modules. Copied from mod-notes.
=> FOLIO-2238 Add missing LaunchDescriptor

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODCR-7 FOLIO-2358 manage container memory

ramls/reserve.json
I don't know how we missed this, but we need this boolean field in the
copyright-tracking subrecord, as described in UICR-9.
=> Add `additionalSectionsUsed` field to copyrightTracking

src/main/resources/sample-data/reserves/Reserve000.json, src/main/resources/sample-data/reserves/Reserve001.json
Previously we were adding complete records with an `itemId`, `copiedItem`, etc. All we need to POST is the `id`, `courseListingId` and `copiedItem.barcode`, and the course-reserves module's logic will pull in the item.
I am not 100% sure that these records will do what we want, because I have not been able to load them against an empty database. But I think they will, and we will find out on tonight's rebuild.
=> Simplify reserves records to be added to database

ramls/copyrightstatuses.json, ramls/courselistings.json, ramls/courses.raml, ramls/coursetypes.json, ramls/processingstatuses.json, src/main/java/org/folio/coursereserves/util/CRUtil.java, src/main/java/org/folio/rest/impl/CourseAPI.java, src/test/java/org/folio/coursereserves/util/UtilVertxTest.java
See https://issues.folio.org/browse/MODCR-25
Tried to build mod-course on Mac laptop but failed with errors like
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mod-courses: Compilation failure: Compilation failure: 
[ERROR] /Users/hji/dev/work/tmp/test/mod-courses/target/generated-sources/raml-jaxrs/org/folio/rest/jaxrs/model/Copyrightstatuses.java:[39,18] cannot find symbol
[ERROR]   symbol:   class CopyrightStatus
```
It turns out that there are similar Java source files generated with just case difference in the name. See below examples. Mac is not case sensitive so some files are overwritten. Those extra files can be removed by tweaking the RAML and json files. This PR addresses that to keep things a bit …
=> MODCR-25: Fix extra generated Java source files with just name case difference

src/main/resources/sample-data/create-records
Previously we were POSTing the sample reserves to `/coursereserves/reserves`. Now we are correctly interpolating the courselisting ID to yield paths like `/coursereserves/courselistings/c03bcba3-a6a0-4251-b316-0631bb2e6f21/reserves`.
=> POST reserves to correct URL within courselisting

src/main/resources/sample-data/create-records
This is the third PR by which I have attempted this trivial task.
=> Remove the *&^&*^ing comment signs from create-records

descriptors/ModuleDescriptor-template.json
This is furnished to the operation
POST /coursereserves/courselistings/{id}/reserves
alongside the existing module permission `inventory-storage.items.item.put`
It should suffice to fix UICR-61.
=> Add inventory-storage.items.collection.get as a modulePermission

ramls/reserve.json, src/main/java/org/folio/coursereserves/util/CRUtil.java, src/test/java/CourseAPITest/CourseAPITest.java, src/test/java/CourseAPITest/OkapiMock.java
First off, sorry about the whitespace, I always have trim-whitespace-on-save enabled. 😆 
Anyway, it does what it says on the tin. We're working on an [Edge API](https://github.com/doytch/edge-lti-courses) that will have URLs for the course reserves that point to patron-accessible sites. SMEs have requested that those URLs be templatable with not just the item barcode, but also instance HRID.
=> Added Instance HRID to copiedItem

descriptors/ModuleDescriptor-template.json
PUT does the same instance/item/holding lookups as POST to add the reserve info, so it needs the same permissions.
This was discovered when attempting to edit a reserve using a user that only had add/edit permissions via [the `ui-courses.add-edit-items` permission](https://github.com/folio-org/ui-courses/blob/633cae7a2f81b164dcca55eed483a46b18360c07/package.json#L113). Theoretically this could also be accomplished in ui-courses' permission sets, but I figured that mirroring the implementation of the solution for the POST endpoint was preferable.
=> Added modulePermissions to PUT reserves route

Jenkinsfile
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-courses section of API documentation will be automatically reconfigured tomorrow:
https://dev.folio.org/reference/api/#explain-gather-config
=> FOLIO-2898 FOLIO-2893 Use new api-doc and api-lint CI facilities

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/impl/CourseAPI.java, src/test/java/CourseAPITest/CourseAPITest.java, src/test/java/CourseAPITest/OkapiMock.java
Allow additional versions for required inventory interfaces:
* item-storage 9.0
* instance-storage 8.0
* holdings-storage 4.0
They add the `_version` property for optimistic locking.
mod-courses uses only one inventory writing API: item PUT.
Error handling code is added to CoursAPI.handleWriteReserves
to handle an item PUT failure.
OkapiMock is extended to always return items with `_version`=6
and checks that item PUT is called with `_version`=6.
=> MODCR-59: item, instande, holding _version optimistic locking

src/main/java/org/folio/coursereserves/util/CRUtil.java, src/test/java/CourseAPITest/OkapiMock.java
CRUtil.lookupItemByBarcode uses
`barcode=$barcode`
This allows CQL injection if $barcode is `*&limit=9999999`
CQL and percent encoding should be used.
The `=` operator (single equals) is the full text search that ignores punctuation, but barcode may contain punctuation.
The `==` operator (two equals) should be used instead, it is an exact match search that is backed by a database index and is fast.
See also https://dev.folio.org/faqs/explain-cql/
=> MODCR-62: Item barcode search: CQL injection, use index, punctuation

src/test/java/CourseAPITest/CourseAPITest.java, src/test/java/org/folio/rest/impl/CourseAPITest.java
Otherwise we may get failures like this:
Expected: a string containing "We've mocked barcode 0 to fail on PUT"
but: was "An error occurred"
Reason:
src/test/java/org/folio/rest/impl/CourseAPITest.java has a test that disables error messages but forgot to re-enable it after the test. If
src/test/java/org/folio/rest/impl/CourseAPITest.java runs before
src/test/java/CourseAPITest/CourseAPITest.java the test fails, otherwise it succeeds.
=> Reset using CourseAPI.setSuppressErrors(false)

ramls/reserve.json, src/main/java/org/folio/coursereserves/util/CRUtil.java, src/test/java/CourseAPITest/CourseAPITest.java, src/test/java/CourseAPITest/OkapiMock.java
[MODCR-65](https://issues.folio.org/browse/MODCR-65): Pull the instance's `discoverySuppress` into the `copiedItem`
=> MODCR-65: Add discoverySuppress to copiedItem

ramls/courses.raml, src/main/java/org/folio/rest/impl/CourseAPI.java, src/test/java/CourseAPITest/CourseAPITest.java, src/test/java/CourseAPITest/TestUtil.java
CourseAPI.java has this code with CQL injection:
String.format("courseListingId = %s", listingId)
String.format("DELETE FROM %s_%s.%s WHERE jsonb->>'courseListingId' = '%s'",
tenantId, "mod_courses", COURSES_TABLE, listingId);
The listingId variable is used without validation and without
masking of CQL or SQL characters resulting in CQL and SQL injection.
Solution:
Use
StringUtil.cqlEncode(listingId)
to wrap correctly wrap and encode the linstingId.
For delete use RMB's PgUtil.delete to avoid duplicate code and
to avoid any CQL and SQL injection.
Note that
courseListingId =
is a full text search and is a wrong operator. Instead
courseListingId ==
is used to make use of the b-tree index that RMB has automatically
created for this foreign key field.
=> MODCR-66: CQL/SQL injection courseListingId

descriptors/ModuleDescriptor-template.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-courses is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-courses.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json
=> MODCR-89: instance-storage 9.0, holdings-storage 6.0, item-storage 10.0

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/courses.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODCR-110 Use GitHub Workflows api-lint and api-schema-lint and api-doc

NEWS.md, descriptors/ModuleDescriptor-template.json
[MODCR-128](https://folio-org.atlassian.net/browse/MODCR-128)
Upgrade the API version in the ModuleDescriptor-template.json:
-`holdings-storage 8.0`
=> MODCR-128 - Upgrade "holdings-storage" API

.github/workflows/postgres.yml, README.md, pom.xml
https://folio-org.atlassian.net/browse/MODCR-136
=> MODCR-136: Update all dependencies for Sunflower (R1-2025)
